#!/bin/sh

curl -XDELETE "http://localhost:9200/blog"
echo

curl -XPOST "http://localhost:9200/blog" -d '{
	"settings": {
		"index.number_of_shards": 1,
		"index.number_of_replicas": 0
	},
	"mappings": {
		"user": {
			"properties": {
				"username": {"type": "string", "index": "not_analyzed"},
				"password": {
					"type": "string",
					"index": "not_analyzed",
					"include_in_all": false
				},
				"email": {"type": "string", "index": "not_analyzed"}
			}
		},
		"post": {
			"properties": {
				"user_id": {"type": "string", "index": "not_analyzed"},
				"title": {"type": "string"},
				"body": {"type": "string"}
			}
		},
		"comment": {
			"_parent": { "type": "post" },
			"properties": {
				"user_id": {"type": "string", "index": "not_analyzed"},
				"body": {"type": "string"}
			}
		}
	}
}'
echo

curl -XPOST "http://localhost:9200/blog/post" -d '{
	"title": "hello world",
	"body": "insert blog post here"
}'
echo
