#!/bin/sh

curl -XDELETE "http://localhost:9200/helloeveryone"
echo

curl -XPOST "http://localhost:9200/helloeveryone" -d '{
	"settings": {
		"index.number_of_shards": 1,
		"index.number_of_replicas": 0
	},
	"mappings": {
		"person": {
			"properties": {
				"timestamp": {"type": "date", "index": "not_analyzed"},
				"name": {"type": "string", "index": "not_analyzed"}
			}
		}
	}
}'
echo
